<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    use SoftDeletes;

    protected $fillable = [
        'contact',
        'ids',
        'email',
        "point",
        'name',
        'address',
        'address_detail',
        'address_zipcode',

        'password',
        "verified_at",
        "social_id",
        "social_platform",
        "accepted",
        "agree_ad",
        "order_name",
        "order_contact",
        "reason_leave_out",
        "elevator",

        "account",
        "bank",
        "owner"
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $appends = ["img"];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($model){
            $model->cart()->create();
        });
    }

    public function registerMediaCollections():void
    {
        $this->addMediaCollection('img')->singleFile();
    }

    public function getImgAttribute()
    {
        if($this->hasMedia('img')) {
            $media = $this->getMedia('img')[0];

            return [
                "name" => $media->file_name,
                "url" => $media->getFullUrl()
            ];
        }

        return null;
    }

    public function cart()
    {
        return $this->hasOne(Cart::class);
    }

    public function deliveries()
    {
        return $this->hasMany(Delivery::class);
    }

    public function coupons()
    {
        return $this->belongsToMany(Coupon::class)->withPivot(["used", "expired_at"]);
    }

    public function validCoupons()
    {
        return $this->coupons()
            ->wherePivot("used", false)
            ->wherePivot("expired_at", ">=", Carbon::now()->startOfDay()->format("Y-m-d"));
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function refunds()
    {
        return $this->hasMany(Refund::class);
    }

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }

    public function orderProducts()
    {
        return $this->hasMany(OrderProduct::class);
    }

    public function outgoings()
    {
        return $this->hasManyThrough(Outgoing::class, Order::class);
    }

    public function likes()
    {
        return $this->hasMany(Like::class);
    }

    public function qnas()
    {
        return $this->hasMany(Qna::class);
    }

    public function latestProducts()
    {
        return $this->hasMany(LatestProduct::class)->orderBy("updated_at", "desc");
    }

    public function template()
    {
        return $this->belongsTo(Template::class);
    }

}
